[project]
name = "anchor-allied"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "python-dotenv",
    "pymongo",
    "fastapi",
    "uvicorn",
    "pydantic",
    "pillow",
    "python-multipart",
    "httpx",
    "groq",
    "python-docx",
    "PyMuPDF",
    "sentence_transformers",
    "pandas",
    "openpyxl",
    "torch==2.7.0",
    "fireworks-ai>=0.0.1a1", # ← allow pre-release versions
    "openai",
]

[tool.uv]
prerelease = "if-necessary-or-explicit"   # ← tell uv to allow pre-releases

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cpu"
